name: ai4i
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow>=1.0
    - pandas~=1.3.2
    - flask~=2.0.1
    - scikit-learn~=0.24.2
    - joblib~=1.0.1
    - numpy~=1.21.2
    - flask-cors